### ISSUE TITLE
Create RBAC contract

### ISSUE THREAD

**Issue by LNow** [syvita/daoOS#15]
Create simple RBAC (Role Based Access Control) clarity contract that will allow us manage who can call which function in our contract/contracts based on role assign to him/her.

Contract should let us:
- grant permission to role
- revoke permission from role
- check if role have a specific permission
- grant role to user
- revoke role from user
- check if user have a specific role
- check if user have a permission based on roles assigned to him/her

To secure contract functions we should be able to write code like below:
```lisp
(define-public (very-important-function)
  (begin
    (asserts! (can-execute "very-important-function") (err "Unauthorized to call this function"))
    ;;
    ;; here rest of the logic
  )
)
```
and only users with assigned roles that have been granted the `very-important-function` permission will be able to execute this function.

**Comment by JMKJR** [comment]
Great initiative! I know we've changed our minds on users/roles a few times. Could we summarize/document here what our final understanding is of what these users and roles are? @labs3/daoos Thanks!

**Comment by LNow** [comment]
I'm not very good at describing technical concepts in a friendly, non-geeky way, but I'll try. Later we can think about more formal documentation.

**Roles** will be identified as unsigned integers 0-127. So in total we can have up to 128 different roles.
In clarity unsigned integers are 128 bit numbers, hence the range 0-127.
Users can have more than one role assigned we'll handle that using bit-masking: One bit in number represents one role. If bit is equal 1 - role is assigned, if it is equal 0 - role is not assigned.

|Roles assigned to user| Binary representation | Decimal representation (this is what we store in contract) |Comment|
|---|---|---|---|
|0 | 000001 | 1 | 2^0 = 1|
|1 | 000010 | 2 | 2^1 = 2|
|2 | 000100 | 4 | 2^2 = 4|
|3 | 001000 | 8 | 2^3 = 8|
|0 and 2| 000101 | 5 | 2^0 + 2^2 = 5| 
|0 and 2 and 3 | 001101| 13 | 2^0 + 2^2 + 2^3 = 13|
|... |...|... |...|
|all 128 roles | 111...111 (128 ones) | 340282366920938463463374607431768211455| 2^0 + 2^1 + ... + 2^127 = 340282366920938463463374607431768211455|


**Permissions** are just unique strings or buffers to which we assign roles in exactly the same way as described above.
I think permission names should be exactly the same as functions they are guarding - for the sake of simplicity.

One user can have multiple roles.
One permission can be granted to multiple roles.

**What are the benefits?**
Let's say we have a role `10` that for simplicity we call `VOTING_MEMBER`.
And we also have a role `11` that we call `STANDARD_MEMBER`.
We create permissions: `vote`, `create-proposal` and assign them to roles as follows:

|ROLE|PERMISSIONS|
|-|-|
|VOTING_MEMBER|`vote`|
|STANDARD_MEMBER|`create-proposal`|

And we have 2 functions:
```lisp
(define-public (vote)
  (begin
    (asserts! (can-execute "vote") (err "Unauthorized to call this function"))
    ;;
    ;; here rest of the logic
  )
)

(define-public (create-proposal)
  (begin
    (asserts! (can-execute "create-proposal") (err "Unauthorized to call this function"))
    ;;
    ;; here rest of the logic
  )
)
```

If you are `VOTING_MEMBER` you can call `vote` without any problems, but you won't be allowed to call `create-proposal`, as only users who have `STANDARD_MEMBER` role can do that.

Now imagine that we have 100 users just like you, and we want to allow them to call `create-proposal`. 
We can grant them `STANDARD_MEMBER` role, but it would be quite expensive as we would have to modify 100 entries (one entry per user). So instead of doing that, we grant `create-proposal` permission to `VOTING_MEMBER` role (1 operation).

|ROLE|PERMISSIONS|
|-|-|
|VOTING_MEMBER|`vote` `create-proposal`|
|STANDARD_MEMBER|`create-proposal`|

And with just one modification (one contract call), we granted permission to call `create-proposal` to all existing and future `VOTING_MEMBERS`.

**Comment by JMKJR** [comment]
@LNow Makes perfect sense to me! Love it! From my perspective, we don't even need to know what the roles and permissions are to make this contract. Those details can be added at runtime. You've documented it perfectly. Have you started implementation on this yet? If not, let me know if you want help or a code review :)

**Comment by LNow** [comment]
@JMKJR you can find ongoing work in this branch: https://github.com/LNow/daoOS/commits/RBAC-contract
