### ISSUE TITLE
Detailed  Architecture

### ISSUE THREAD

**Issue by falkonprods** [syvita/daoOS#2]
Need to create a comprehensive  architecture detailing  out what  needs  to be built,  what libraries can be used, etc. This should ideally be a recipe card to streamline development. For example, we should list out what smart contracts will need to  be  built and what the key operations are that  they will each handle.

**Comment by pxydn** [comment]
@LNow created a good diagram to start us off on this.

![DAO_-_Contract_component_diagram](https://user-images.githubusercontent.com/67651251/115570396-fc439580-a2b5-11eb-9bfa-f1e2f0c783ed.png)
