### ISSUE TITLE
Workflows of Application

### ISSUE THREAD

**Issue by falkonprods** [syvita/daoOS#4]
Wireframe showing the key flow of the application

https://miro.com/welcomeonboard/EgAzzSZ0GZrB8SilD9fgdq4pqzLOP7Ewpkz1cnxLerLGy6z89u7LbkB6gJAiQtXG

**Comment by JMKJR** [comment]
Linking our figma here https://www.figma.com/file/Yfmu9x1lpnL3zIAyaG2oTM/Labs3-Design-System?node-id=1569%3A0

**Comment by JMKJR** [comment]
We already have an issue created for design, so by wireframe do you mean flowchart(s)? @falkonprods
