### ISSUE TITLE
How we should secure the private key of Treasury account on DAO contract? 

### ISSUE THREAD

**Issue by cryptopanter** [syvita/daoos#46]
Since the Treasury account must be governed by voting members (am I right?) then we need sth like a multisignature wallet controlled by voters( or admin)... The challenge is that how to implement the multisignature wallet on smart contract!

**Comment by asteriabtc** [comment]
smart contracts have their own balances that only the contract can control! you don't need a multisig because the contract itself has direct access and programmatic control of its assets (STX, fungible tokens & NFTs)
