### ISSUE TITLE
Tests failing in contracts package

### ISSUE THREAD

**Issue by JMKJR** [syvita/daoos#49]
Our tests are failing in the `contracts` package on our `main` branch.

**To Reproduce**
1. Checkout `main`
2. `npm i` from within `packages/contracts` to install packages.
3. Run `npm test` from within the same directory.
4. 1/4 tests are passing. The error is the same for the 3 failing tests and is as follows...
`ExecutionError: Eval expression on contract failed with bad exit code 1: Program execution error: 
Unchecked(UndefinedFunction("get-counter"))`

**Expected behavior**
All tests should pass.

**Additional context**
Perhaps this is due to a lack of understanding on my behalf of how to run these tests. In which case, let me know the appropriate steps, and I will close the erroneously filed bug report. I can investigate this after #37 is merged if this remains unassigned.

**Comment by LNow** [comment]
All tests related to counter contract can and should be removed. Same thing applies to `counter.clar` contract. It is just an initial contract created by stacks library, but we don't need it as we have to write our own contracts and test suites.

**Comment by JMKJR** [comment]
> All tests related to counter contract can and should be removed. Same thing applies to `counter.clar` contract. It is just an initial contract created by stacks library, but we don't need it as we have to write our own contracts and test suites.

Ok thanks.
